server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/carrental}
    username: ${SPRING_DATASOURCE_USERNAME:carrental}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    secret: ${APP_JWT_SECRET:DYOKLYRVAeBuprgaqNsKe8hnAWaQudwjmaSquuxy9og=}
    access-minutes: ${APP_JWT_ACCESS_MINUTES:15}
    refresh-days: ${APP_JWT_REFRESH_DAYS:30}