spring:
  application:
    name: car-service
  datasource:
    url: jdbc:postgresql://localhost:5432/carrental
    username: jasonzeng
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  logging:
    level:
      org.hibernate.SQL: debug

server:
  port: 8082